from datetime import date
from fastapi import APIRouter,Query,Response
from . import service as s
from .dependencies import CurrentUser,DB
from .schemas import *
router=APIRouter()
@router.get("/dashboard",response_model=Dashboard,operation_id="getNetWorthDashboard")
def dashboard(db:DB,current_user:CurrentUser):return s.dashboard(db,current_user)
@router.get("/accounts",response_model=AccountList,operation_id="listNetWorthAccounts")
def accounts(db:DB,current_user:CurrentUser,q:str|None=None,account_type:AccountType|None=Query(None,alias="accountType"),category:str|None=None,currency:str|None=None,status:Status|None=None,included:bool|None=None,updated_from:date|None=Query(None,alias="updatedFrom"),updated_to:date|None=Query(None,alias="updatedTo"),page:int=Query(1,ge=1),page_size:int=Query(12,alias="pageSize",ge=1,le=100)):return s.list_accounts(db,current_user,q,account_type,category,currency,status,included,updated_from,updated_to,page,page_size)
@router.post("/accounts",response_model=AccountDetail,status_code=201,operation_id="createNetWorthAccount")
def ca(payload:AccountCreate,db:DB,current_user:CurrentUser):return s.save_account(db,current_user,payload)
@router.get("/accounts/{account_id}",response_model=AccountDetail,operation_id="getNetWorthAccount")
def ga(account_id:str,db:DB,current_user:CurrentUser):return s.get_account(db,current_user,account_id)
@router.put("/accounts/{account_id}",response_model=AccountDetail,operation_id="updateNetWorthAccount")
def ua(account_id:str,payload:AccountUpdate,db:DB,current_user:CurrentUser):return s.save_account(db,current_user,payload,account_id)
@router.delete("/accounts/{account_id}",status_code=204,operation_id="deleteNetWorthAccount")
def da(account_id:str,db:DB,current_user:CurrentUser):s.delete_account(db,current_user,account_id);return Response(status_code=204)
@router.post("/accounts/{account_id}/balances",response_model=AccountDetail,status_code=201,operation_id="createNetWorthBalanceEntry")
def cb(account_id:str,payload:BalanceCreate,db:DB,current_user:CurrentUser):return s.save_entry(db,current_user,account_id,payload)
@router.put("/accounts/{account_id}/balances/{entry_id}",response_model=AccountDetail,operation_id="updateNetWorthBalanceEntry")
def ub(account_id:str,entry_id:str,payload:BalanceUpdate,db:DB,current_user:CurrentUser):return s.save_entry(db,current_user,account_id,payload,entry_id)
@router.delete("/accounts/{account_id}/balances/{entry_id}",status_code=204,operation_id="deleteNetWorthBalanceEntry")
def dbal(account_id:str,entry_id:str,db:DB,current_user:CurrentUser):s.delete_entry(db,current_user,account_id,entry_id);return Response(status_code=204)
@router.get("/snapshots",response_model=SnapshotList,operation_id="listNetWorthSnapshots")
def snapshots(db:DB,current_user:CurrentUser,q:str|None=None,date_from:date|None=Query(None,alias="dateFrom"),date_to:date|None=Query(None,alias="dateTo"),page:int=Query(1,ge=1),page_size:int=Query(12,alias="pageSize",ge=1,le=100)):return s.list_snapshots(db,current_user,q,date_from,date_to,page,page_size)
@router.post("/snapshots",response_model=SnapshotDetail,status_code=201,operation_id="createNetWorthSnapshot")
def cs(payload:SnapshotCreate,db:DB,current_user:CurrentUser):return s.create_snapshot(db,current_user,payload)
@router.get("/snapshots/{snapshot_id}",response_model=SnapshotDetail,operation_id="getNetWorthSnapshot")
def gs(snapshot_id:str,db:DB,current_user:CurrentUser):return s.get_snapshot(db,current_user,snapshot_id)
@router.delete("/snapshots/{snapshot_id}",status_code=204,operation_id="deleteNetWorthSnapshot")
def ds(snapshot_id:str,db:DB,current_user:CurrentUser):s.delete_snapshot(db,current_user,snapshot_id);return Response(status_code=204)
@router.get("/compare",response_model=Comparison,operation_id="compareNetWorthSnapshots")
def compare(db:DB,current_user:CurrentUser,previous_id:str=Query(alias="previousId"),current_id:str=Query(alias="currentId")):return s.compare(db,current_user,previous_id,current_id)
