from datetime import date,datetime
from uuid import uuid4
from sqlalchemy import Boolean,Date,DateTime,ForeignKey,Index,Integer,String,Text,UniqueConstraint,func
from sqlalchemy.orm import Mapped,mapped_column,relationship
from .db import Base
def uid():return str(uuid4())
class ServiceCategory(Base):
 __tablename__="ServiceCategories";__table_args__=(UniqueConstraint("userId","name",name="uq_service_category_user_name"),Index("ix_service_categories_user_sort","userId","sortOrder"),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);user_id:Mapped[str]=mapped_column("userId",String(36),index=True);name:Mapped[str]=mapped_column(String(80));color:Mapped[str|None]=mapped_column(String(40));sort_order:Mapped[int]=mapped_column("sortOrder",Integer,default=0);created_at:Mapped[datetime]=mapped_column("createdAt",DateTime,server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime,server_default=func.now(),onupdate=func.now());providers:Mapped[list["ServiceProvider"]]=relationship(back_populates="category")
class ServiceProvider(Base):
 __tablename__="ServiceProviders";__table_args__=(Index("ix_service_providers_user_category","userId","categoryId"),Index("ix_service_providers_user_archived","userId","archived"),Index("ix_service_providers_user_preferred","userId","preferred"),Index("ix_service_providers_user_rating","userId","rating"),Index("ix_service_providers_user_last_contacted","userId","lastContacted"),Index("ix_service_providers_user_updated","userId","updatedAt"),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);user_id:Mapped[str]=mapped_column("userId",String(36),index=True);category_id:Mapped[str|None]=mapped_column("categoryId",String(36),ForeignKey("ServiceCategories.id",ondelete="SET NULL"),index=True);business_name:Mapped[str]=mapped_column("businessName",String(180));contact_person:Mapped[str|None]=mapped_column("contactPerson",String(120));phone:Mapped[str|None]=mapped_column(String(40));alternate_phone:Mapped[str|None]=mapped_column("alternatePhone",String(40));email:Mapped[str|None]=mapped_column(String(180));website:Mapped[str|None]=mapped_column(String(240));address:Mapped[str|None]=mapped_column(Text);city:Mapped[str|None]=mapped_column(String(120));area:Mapped[str|None]=mapped_column(String(120));notes:Mapped[str|None]=mapped_column(Text);rating:Mapped[int|None]=mapped_column(Integer);preferred:Mapped[bool]=mapped_column(Boolean,default=False);archived:Mapped[bool]=mapped_column(Boolean,default=False);last_contacted:Mapped[date|None]=mapped_column("lastContacted",Date);created_at:Mapped[datetime]=mapped_column("createdAt",DateTime,server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime,server_default=func.now(),onupdate=func.now());category:Mapped[ServiceCategory|None]=relationship(back_populates="providers")
