from datetime import date
from fastapi import APIRouter,Query,Response
from . import service as s
from .dependencies import CurrentUser,DB
from .schemas import *
router=APIRouter()
@router.get("/dashboard",response_model=Dashboard,operation_id="getLocalServicesFinderDashboard")
def dashboard(db:DB,current_user:CurrentUser):return s.dashboard(db,current_user)
@router.get("/providers",response_model=ProviderList,operation_id="listServiceProviders")
def providers(db:DB,current_user:CurrentUser,q:str|None=None,category_id:str|None=Query(None,alias="categoryId"),preferred:bool|None=None,archived:bool|None=None,rating:int|None=Query(None,ge=1,le=5),last_contacted_from:date|None=Query(None,alias="lastContactedFrom"),last_contacted_to:date|None=Query(None,alias="lastContactedTo"),page:int=Query(1,ge=1),page_size:int=Query(12,alias="pageSize",ge=1,le=100)):return s.list_providers(db,current_user,q,category_id,preferred,archived,rating,last_contacted_from,last_contacted_to,page,page_size)
@router.post("/providers",response_model=ProviderDetail,status_code=201,operation_id="createServiceProvider")
def create_provider(payload:ProviderCreate,db:DB,current_user:CurrentUser):return s.save_provider(db,current_user,payload)
@router.get("/providers/{provider_id}",response_model=ProviderDetail,operation_id="getServiceProvider")
def get_provider(provider_id:str,db:DB,current_user:CurrentUser):return s.get_provider(db,current_user,provider_id)
@router.put("/providers/{provider_id}",response_model=ProviderDetail,operation_id="updateServiceProvider")
def update_provider(provider_id:str,payload:ProviderUpdate,db:DB,current_user:CurrentUser):return s.save_provider(db,current_user,payload,provider_id)
@router.delete("/providers/{provider_id}",status_code=204,operation_id="deleteServiceProvider")
def delete_provider(provider_id:str,db:DB,current_user:CurrentUser):s.delete_provider(db,current_user,provider_id);return Response(status_code=204)
@router.post("/providers/{provider_id}/archive",response_model=ProviderDetail,operation_id="archiveServiceProvider")
def archive(provider_id:str,db:DB,current_user:CurrentUser):return s.archive(db,current_user,provider_id)
@router.post("/providers/{provider_id}/restore",response_model=ProviderDetail,operation_id="restoreServiceProvider")
def restore(provider_id:str,db:DB,current_user:CurrentUser):return s.restore(db,current_user,provider_id)
@router.post("/providers/{provider_id}/prefer",response_model=ProviderDetail,operation_id="preferServiceProvider")
def prefer(provider_id:str,db:DB,current_user:CurrentUser):return s.set_preferred(db,current_user,provider_id,True)
@router.post("/providers/{provider_id}/unprefer",response_model=ProviderDetail,operation_id="unpreferServiceProvider")
def unprefer(provider_id:str,db:DB,current_user:CurrentUser):return s.set_preferred(db,current_user,provider_id,False)
@router.get("/categories",response_model=CategoryList,operation_id="listServiceCategories")
def categories(db:DB,current_user:CurrentUser,q:str|None=None,page:int=Query(1,ge=1),page_size:int=Query(50,alias="pageSize",ge=1,le=100)):return s.list_categories(db,current_user,q,page,page_size)
@router.post("/categories",response_model=CategoryResponse,status_code=201,operation_id="createServiceCategory")
def create_category(payload:CategoryCreate,db:DB,current_user:CurrentUser):return s.save_category(db,current_user,payload)
@router.put("/categories/{category_id}",response_model=CategoryResponse,operation_id="updateServiceCategory")
def update_category(category_id:str,payload:CategoryUpdate,db:DB,current_user:CurrentUser):return s.save_category(db,current_user,payload,category_id)
@router.delete("/categories/{category_id}",status_code=204,operation_id="deleteServiceCategory")
def delete_category(category_id:str,db:DB,current_user:CurrentUser):s.delete_category(db,current_user,category_id);return Response(status_code=204)
