"""Create Savings Goal Planner tables."""
from alembic import op
import sqlalchemy as sa
revision="20260716_0006_savings_goal_planner";down_revision=None;branch_labels=None;depends_on=None
M=sa.Numeric(14,2)
def upgrade():
 op.create_table("SavingsGoals",sa.Column("id",sa.String(36),primary_key=True),sa.Column("userId",sa.String(36),nullable=False),sa.Column("name",sa.String(180),nullable=False),sa.Column("description",sa.Text()),sa.Column("category",sa.String(24),nullable=False),sa.Column("currencyCode",sa.String(3),nullable=False),sa.Column("targetAmount",M,nullable=False),sa.Column("startingAmount",M,nullable=False),sa.Column("currentAmount",M,nullable=False),sa.Column("targetDate",sa.Date()),sa.Column("priority",sa.String(12),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("notes",sa.Text()),sa.Column("createdAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updatedAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False))
 for n,c in [("ix_savings_goals_user_id",["userId"]),("ix_savings_goals_category",["category"]),("ix_savings_goals_priority",["priority"]),("ix_savings_goals_status",["status"]),("ix_savings_goals_target_date",["targetDate"]),("ix_savings_goals_user_status",["userId","status"]),("ix_savings_goals_user_target_date",["userId","targetDate"]),("ix_savings_goals_user_currency",["userId","currencyCode"]),("ix_savings_goals_user_category",["userId","category"])]:op.create_index(n,"SavingsGoals",c)
 op.create_table("SavingsTransactions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("goalId",sa.String(36),sa.ForeignKey("SavingsGoals.id",ondelete="CASCADE"),nullable=False),sa.Column("transactionDate",sa.Date(),nullable=False),sa.Column("transactionType",sa.String(24),nullable=False),sa.Column("amount",M,nullable=False),sa.Column("description",sa.String(300)),sa.Column("notes",sa.Text()),sa.Column("createdAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updatedAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False));op.create_index("ix_savings_transactions_goal_id","SavingsTransactions",["goalId"]);op.create_index("ix_savings_transactions_date","SavingsTransactions",["transactionDate"]);op.create_index("ix_savings_transactions_type","SavingsTransactions",["transactionType"]);op.create_index("ix_savings_transactions_goal_date","SavingsTransactions",["goalId","transactionDate"])
 op.create_table("SavingsMilestones",sa.Column("id",sa.String(36),primary_key=True),sa.Column("goalId",sa.String(36),sa.ForeignKey("SavingsGoals.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(180),nullable=False),sa.Column("targetAmount",M,nullable=False),sa.Column("targetDate",sa.Date()),sa.Column("status",sa.String(16),nullable=False),sa.Column("sortOrder",sa.Integer(),nullable=False),sa.Column("notes",sa.Text()),sa.Column("createdAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updatedAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False));op.create_index("ix_savings_milestones_goal_id","SavingsMilestones",["goalId"]);op.create_index("ix_savings_milestones_goal_sort","SavingsMilestones",["goalId","sortOrder"])
def downgrade():op.drop_table("SavingsMilestones");op.drop_table("SavingsTransactions");op.drop_table("SavingsGoals")
