"""Create Bill Splitter tables."""
from alembic import op
import sqlalchemy as sa
revision="20260716_0005_bill_splitter";down_revision=None;branch_labels=None;depends_on=None
M=sa.Numeric(14,2)
def upgrade():
 op.create_table("Bills",sa.Column("id",sa.String(36),primary_key=True),sa.Column("userId",sa.String(36),nullable=False),sa.Column("title",sa.String(180),nullable=False),sa.Column("billDate",sa.Date(),nullable=False),sa.Column("merchantName",sa.String(180)),sa.Column("currencyCode",sa.String(3),nullable=False),sa.Column("discountAmount",M,nullable=False),sa.Column("taxAmount",M,nullable=False),sa.Column("serviceChargeAmount",M,nullable=False),sa.Column("tipAmount",M,nullable=False),sa.Column("subtotalAmount",M,nullable=False),sa.Column("totalAmount",M,nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("notes",sa.Text()),sa.Column("createdAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updatedAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False))
 for n,c in [("ix_bills_user_id",["userId"]),("ix_bills_date",["billDate"]),("ix_bills_status",["status"]),("ix_bills_user_date",["userId","billDate"]),("ix_bills_user_status",["userId","status"]),("ix_bills_user_currency",["userId","currencyCode"])]:op.create_index(n,"Bills",c)
 op.create_table("BillParticipants",sa.Column("id",sa.String(36),primary_key=True),sa.Column("billId",sa.String(36),sa.ForeignKey("Bills.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(120),nullable=False),sa.Column("email",sa.String(254)),sa.Column("paidAmount",M,nullable=False),sa.Column("shareAmount",M,nullable=False),sa.Column("settlementStatus",sa.String(24),nullable=False),sa.Column("notes",sa.Text()),sa.Column("sortOrder",sa.Integer(),nullable=False),sa.Column("createdAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updatedAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.UniqueConstraint("billId","name"));op.create_index("ix_bill_participants_bill_id","BillParticipants",["billId"]);op.create_index("ix_bill_participants_bill_sort","BillParticipants",["billId","sortOrder"])
 op.create_table("BillItems",sa.Column("id",sa.String(36),primary_key=True),sa.Column("billId",sa.String(36),sa.ForeignKey("Bills.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(180),nullable=False),sa.Column("quantity",sa.Numeric(12,2),nullable=False),sa.Column("unitPrice",M,nullable=False),sa.Column("lineTotal",M,nullable=False),sa.Column("splitMethod",sa.String(24),nullable=False),sa.Column("notes",sa.Text()),sa.Column("sortOrder",sa.Integer(),nullable=False),sa.Column("createdAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updatedAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False));op.create_index("ix_bill_items_bill_id","BillItems",["billId"]);op.create_index("ix_bill_items_bill_sort","BillItems",["billId","sortOrder"])
 op.create_table("BillItemAllocations",sa.Column("id",sa.String(36),primary_key=True),sa.Column("billItemId",sa.String(36),sa.ForeignKey("BillItems.id",ondelete="CASCADE"),nullable=False),sa.Column("participantId",sa.String(36),sa.ForeignKey("BillParticipants.id"),nullable=False),sa.Column("allocationAmount",M,nullable=False),sa.Column("createdAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updatedAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.UniqueConstraint("billItemId","participantId"));op.create_index("ix_allocations_item_id","BillItemAllocations",["billItemId"]);op.create_index("ix_allocations_participant_id","BillItemAllocations",["participantId"])
def downgrade():op.drop_table("BillItemAllocations");op.drop_table("BillItems");op.drop_table("BillParticipants");op.drop_table("Bills")
