"""add_apps_catalog_table

Revision ID: a7e246b7249d
Revises: fb046b3b8a1f
Create Date: 2026-05-28 19:38:36.447011

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "a7e246b7249d"
down_revision: str | None = "fb046b3b8a1f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apps",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=40), server_default="active", nullable=False),
        sa.Column(
            "launch_status",
            sa.String(length=40),
            server_default="comingSoon",
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.String(length=40),
            server_default="public",
            nullable=False,
        ),
        sa.Column("website_url", sa.String(length=500), nullable=True),
        sa.Column("admin_url", sa.String(length=500), nullable=True),
        sa.Column("logo_key", sa.String(length=120), nullable=True),
        sa.Column("is_featured", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_apps_key"), "apps", ["key"], unique=True)
    op.create_index(op.f("ix_apps_slug"), "apps", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_apps_slug"), table_name="apps")
    op.drop_index(op.f("ix_apps_key"), table_name="apps")
    op.drop_table("apps")
    # ### end Alembic commands ###
