"""Create Shift Planner tables."""
from alembic import op
import sqlalchemy as sa
revision="20260716_0003_shift_planner";down_revision=None;branch_labels=None;depends_on=None
def upgrade():
    op.create_table("ShiftTypes",sa.Column("id",sa.String(36),primary_key=True),sa.Column("userId",sa.String(36),nullable=False),sa.Column("name",sa.String(120),nullable=False),sa.Column("code",sa.String(30)),sa.Column("description",sa.Text()),sa.Column("defaultStartTime",sa.Time(),nullable=False),sa.Column("defaultEndTime",sa.Time(),nullable=False),sa.Column("defaultBreakMinutes",sa.Integer(),nullable=False),sa.Column("colorKey",sa.String(20),nullable=False),sa.Column("isActive",sa.Boolean(),nullable=False),sa.Column("createdAt",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updatedAt",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.UniqueConstraint("userId","name",name="uq_shift_types_user_name"));op.create_index("ix_shift_types_user_id","ShiftTypes",["userId"]);op.create_index("ix_shift_types_user_active","ShiftTypes",["userId","isActive"])
    op.create_table("ShiftMembers",sa.Column("id",sa.String(36),primary_key=True),sa.Column("userId",sa.String(36),nullable=False),sa.Column("name",sa.String(120),nullable=False),sa.Column("email",sa.String(254)),sa.Column("phone",sa.String(50)),sa.Column("role",sa.String(100)),sa.Column("notes",sa.Text()),sa.Column("isActive",sa.Boolean(),nullable=False),sa.Column("createdAt",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updatedAt",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False));op.create_index("ix_shift_members_user_id","ShiftMembers",["userId"]);op.create_index("ix_shift_members_user_active","ShiftMembers",["userId","isActive"])
    op.create_table("Shifts",sa.Column("id",sa.String(36),primary_key=True),sa.Column("userId",sa.String(36),nullable=False),sa.Column("shiftTypeId",sa.String(36),sa.ForeignKey("ShiftTypes.id"),nullable=False),sa.Column("memberId",sa.String(36),sa.ForeignKey("ShiftMembers.id")),sa.Column("title",sa.String(180),nullable=False),sa.Column("shiftDate",sa.Date(),nullable=False),sa.Column("startTime",sa.Time(),nullable=False),sa.Column("endTime",sa.Time(),nullable=False),sa.Column("breakMinutes",sa.Integer(),nullable=False),sa.Column("durationMinutes",sa.Integer(),nullable=False),sa.Column("location",sa.String(250)),sa.Column("status",sa.String(20),nullable=False),sa.Column("notes",sa.Text()),sa.Column("createdAt",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updatedAt",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False))
    for n,c in [("ix_shifts_user_id",["userId"]),("ix_shifts_type_id",["shiftTypeId"]),("ix_shifts_member_id",["memberId"]),("ix_shifts_date",["shiftDate"]),("ix_shifts_status",["status"]),("ix_shifts_user_date",["userId","shiftDate"]),("ix_shifts_user_status",["userId","status"]),("ix_shifts_user_member_date",["userId","memberId","shiftDate"])]:op.create_index(n,"Shifts",c)
def downgrade():op.drop_table("Shifts");op.drop_table("ShiftMembers");op.drop_table("ShiftTypes")
