from datetime import date
from fastapi import APIRouter,Query,Response
from . import service as s
from .dependencies import CurrentUser,DB
from .schemas import *
router=APIRouter()
@router.get("/dashboard",response_model=Dashboard,operation_id="getErrandPlannerDashboard")
def dashboard(db:DB,current_user:CurrentUser):return s.dashboard(db,current_user)
@router.get("/errands",response_model=ErrandList,operation_id="listErrands")
def errands(db:DB,current_user:CurrentUser,q:str|None=None,status:Status|None=None,category_id:str|None=Query(None,alias="categoryId"),priority:Priority|None=None,overdue:bool|None=None,due_today:bool|None=Query(None,alias="dueToday"),due_soon:bool|None=Query(None,alias="dueSoon"),due_from:date|None=Query(None,alias="dueFrom"),due_to:date|None=Query(None,alias="dueTo"),page:int=Query(1,ge=1),page_size:int=Query(12,alias="pageSize",ge=1,le=100)):return s.list_errands(db,current_user,q,status,category_id,priority,overdue,due_today,due_soon,due_from,due_to,page,page_size)
@router.post("/errands",response_model=ErrandDetail,status_code=201,operation_id="createErrand")
def create_errand(payload:ErrandCreate,db:DB,current_user:CurrentUser):return s.save_errand(db,current_user,payload)
@router.get("/errands/{errand_id}",response_model=ErrandDetail,operation_id="getErrand")
def get_errand(errand_id:str,db:DB,current_user:CurrentUser):return s.get_errand(db,current_user,errand_id)
@router.put("/errands/{errand_id}",response_model=ErrandDetail,operation_id="updateErrand")
def update_errand(errand_id:str,payload:ErrandUpdate,db:DB,current_user:CurrentUser):return s.save_errand(db,current_user,payload,errand_id)
@router.delete("/errands/{errand_id}",status_code=204,operation_id="deleteErrand")
def delete_errand(errand_id:str,db:DB,current_user:CurrentUser):s.delete_errand(db,current_user,errand_id);return Response(status_code=204)
@router.post("/errands/{errand_id}/complete",response_model=ErrandDetail,operation_id="completeErrand")
def complete(errand_id:str,db:DB,current_user:CurrentUser):return s.set_status(db,current_user,errand_id,"completed")
@router.post("/errands/{errand_id}/reopen",response_model=ErrandDetail,operation_id="reopenErrand")
def reopen(errand_id:str,db:DB,current_user:CurrentUser):return s.set_status(db,current_user,errand_id,"pending")
@router.post("/errands/{errand_id}/archive",response_model=ErrandDetail,operation_id="archiveErrand")
def archive(errand_id:str,db:DB,current_user:CurrentUser):return s.archive(db,current_user,errand_id)
@router.post("/errands/{errand_id}/restore",response_model=ErrandDetail,operation_id="restoreErrand")
def restore(errand_id:str,db:DB,current_user:CurrentUser):return s.restore(db,current_user,errand_id)
@router.get("/categories",response_model=CategoryList,operation_id="listErrandCategories")
def categories(db:DB,current_user:CurrentUser,q:str|None=None,page:int=Query(1,ge=1),page_size:int=Query(50,alias="pageSize",ge=1,le=100)):return s.list_categories(db,current_user,q,page,page_size)
@router.post("/categories",response_model=CategoryResponse,status_code=201,operation_id="createErrandCategory")
def create_category(payload:CategoryCreate,db:DB,current_user:CurrentUser):return s.save_category(db,current_user,payload)
@router.put("/categories/{category_id}",response_model=CategoryResponse,operation_id="updateErrandCategory")
def update_category(category_id:str,payload:CategoryUpdate,db:DB,current_user:CurrentUser):return s.save_category(db,current_user,payload,category_id)
@router.delete("/categories/{category_id}",status_code=204,operation_id="deleteErrandCategory")
def delete_category(category_id:str,db:DB,current_user:CurrentUser):s.delete_category(db,current_user,category_id);return Response(status_code=204)
