from datetime import date,datetime,time
from uuid import uuid4
from sqlalchemy import Boolean,Date,DateTime,ForeignKey,Index,Integer,String,Text,Time,UniqueConstraint,func
from sqlalchemy.orm import Mapped,mapped_column,relationship
from app.modules.shift_planner.db import ShiftPlannerBase
def uid(): return str(uuid4())
class ShiftType(ShiftPlannerBase):
    __tablename__="ShiftTypes"; __table_args__=(UniqueConstraint("userId","name",name="uq_shift_types_user_name"),Index("ix_shift_types_user_active","userId","isActive"))
    id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); owner_id:Mapped[str]=mapped_column("userId",String(36),index=True); name:Mapped[str]=mapped_column(String(120)); code:Mapped[str|None]=mapped_column(String(30)); description:Mapped[str|None]=mapped_column(Text); default_start_time:Mapped[time]=mapped_column("defaultStartTime",Time); default_end_time:Mapped[time]=mapped_column("defaultEndTime",Time); default_break_minutes:Mapped[int]=mapped_column("defaultBreakMinutes",Integer,default=0); color_key:Mapped[str]=mapped_column("colorKey",String(20),default="blue"); is_active:Mapped[bool]=mapped_column("isActive",Boolean,default=True); created_at:Mapped[datetime]=mapped_column("createdAt",DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime(timezone=True),server_default=func.now(),onupdate=func.now()); shifts:Mapped[list["Shift"]]=relationship(back_populates="shift_type")
class ShiftMember(ShiftPlannerBase):
    __tablename__="ShiftMembers"; __table_args__=(Index("ix_shift_members_user_active","userId","isActive"),)
    id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); owner_id:Mapped[str]=mapped_column("userId",String(36),index=True); name:Mapped[str]=mapped_column(String(120)); email:Mapped[str|None]=mapped_column(String(254)); phone:Mapped[str|None]=mapped_column(String(50)); role:Mapped[str|None]=mapped_column(String(100)); notes:Mapped[str|None]=mapped_column(Text); is_active:Mapped[bool]=mapped_column("isActive",Boolean,default=True); created_at:Mapped[datetime]=mapped_column("createdAt",DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime(timezone=True),server_default=func.now(),onupdate=func.now()); shifts:Mapped[list["Shift"]]=relationship(back_populates="member")
class Shift(ShiftPlannerBase):
    __tablename__="Shifts"; __table_args__=(Index("ix_shifts_user_date","userId","shiftDate"),Index("ix_shifts_user_status","userId","status"),Index("ix_shifts_user_member_date","userId","memberId","shiftDate"))
    id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); owner_id:Mapped[str]=mapped_column("userId",String(36),index=True); shift_type_id:Mapped[str]=mapped_column("shiftTypeId",String(36),ForeignKey("ShiftTypes.id"),index=True); member_id:Mapped[str|None]=mapped_column("memberId",String(36),ForeignKey("ShiftMembers.id"),index=True); title:Mapped[str]=mapped_column(String(180)); shift_date:Mapped[date]=mapped_column("shiftDate",Date,index=True); start_time:Mapped[time]=mapped_column("startTime",Time); end_time:Mapped[time]=mapped_column("endTime",Time); break_minutes:Mapped[int]=mapped_column("breakMinutes",Integer,default=0); duration_minutes:Mapped[int]=mapped_column("durationMinutes",Integer); location:Mapped[str|None]=mapped_column(String(250)); status:Mapped[str]=mapped_column(String(20),index=True); notes:Mapped[str|None]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column("createdAt",DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime(timezone=True),server_default=func.now(),onupdate=func.now()); shift_type:Mapped[ShiftType]=relationship(back_populates="shifts"); member:Mapped[ShiftMember|None]=relationship(back_populates="shifts")
