from datetime import date
from fastapi import APIRouter,Query,Response
from app.modules.shift_planner import service
from app.modules.shift_planner.dependencies import CurrentShiftPlannerUser,ShiftPlannerDB
from app.modules.shift_planner.schemas import *
router=APIRouter()
@router.get("/dashboard",response_model=Dashboard,operation_id="getShiftPlannerDashboard")
def dashboard(db:ShiftPlannerDB,current_user:CurrentShiftPlannerUser):return service.dashboard(db,current_user)
@router.get("/types",response_model=list[TypeResponse],operation_id="listShiftPlannerTypes")
def types(db:ShiftPlannerDB,current_user:CurrentShiftPlannerUser):return service.list_types(db,current_user)
@router.post("/types",response_model=TypeResponse,status_code=201,operation_id="createShiftPlannerType")
def create_type(payload:TypeCreate,db:ShiftPlannerDB,current_user:CurrentShiftPlannerUser):return service.save_type(db,current_user,payload)
@router.put("/types/{type_id}",response_model=TypeResponse,operation_id="updateShiftPlannerType")
def update_type(type_id:str,payload:TypeUpdate,db:ShiftPlannerDB,current_user:CurrentShiftPlannerUser):return service.save_type(db,current_user,payload,type_id)
@router.delete("/types/{type_id}",status_code=204,operation_id="deleteShiftPlannerType")
def delete_type(type_id:str,db:ShiftPlannerDB,current_user:CurrentShiftPlannerUser):service.delete_type(db,current_user,type_id);return Response(status_code=204)
@router.get("/members",response_model=list[MemberResponse],operation_id="listShiftPlannerMembers")
def members(db:ShiftPlannerDB,current_user:CurrentShiftPlannerUser):return service.list_members(db,current_user)
@router.post("/members",response_model=MemberResponse,status_code=201,operation_id="createShiftPlannerMember")
def create_member(payload:MemberCreate,db:ShiftPlannerDB,current_user:CurrentShiftPlannerUser):return service.save_member(db,current_user,payload)
@router.put("/members/{member_id}",response_model=MemberResponse,operation_id="updateShiftPlannerMember")
def update_member(member_id:str,payload:MemberUpdate,db:ShiftPlannerDB,current_user:CurrentShiftPlannerUser):return service.save_member(db,current_user,payload,member_id)
@router.delete("/members/{member_id}",status_code=204,operation_id="deleteShiftPlannerMember")
def delete_member(member_id:str,db:ShiftPlannerDB,current_user:CurrentShiftPlannerUser):service.delete_member(db,current_user,member_id);return Response(status_code=204)
@router.get("/shifts",response_model=ShiftList,operation_id="listShiftPlannerShifts")
def shifts(db:ShiftPlannerDB,current_user:CurrentShiftPlannerUser,q:str|None=None,shift_type_id:str|None=Query(None,alias="shiftTypeId"),member_id:str|None=Query(None,alias="memberId"),status_filter:Status|None=Query(None,alias="status"),period:Period="all",date_from:date|None=Query(None,alias="dateFrom"),date_to:date|None=Query(None,alias="dateTo"),page:int=Query(1,ge=1),page_size:int=Query(20,alias="pageSize",ge=1,le=100)):return service.list_shifts(db,current_user,q,shift_type_id,member_id,status_filter,period,date_from,date_to,page,page_size)
@router.post("/shifts",response_model=ShiftResponse,status_code=201,operation_id="createShiftPlannerShift")
def create_shift(payload:ShiftCreate,db:ShiftPlannerDB,current_user:CurrentShiftPlannerUser):return service.save_shift(db,current_user,payload)
@router.get("/shifts/{shift_id}",response_model=ShiftResponse,operation_id="getShiftPlannerShift")
def get_shift(shift_id:str,db:ShiftPlannerDB,current_user:CurrentShiftPlannerUser):return service.get_shift(db,current_user,shift_id)
@router.put("/shifts/{shift_id}",response_model=ShiftResponse,operation_id="updateShiftPlannerShift")
def update_shift(shift_id:str,payload:ShiftUpdate,db:ShiftPlannerDB,current_user:CurrentShiftPlannerUser):return service.save_shift(db,current_user,payload,shift_id)
@router.delete("/shifts/{shift_id}",status_code=204,operation_id="deleteShiftPlannerShift")
def delete_shift(shift_id:str,db:ShiftPlannerDB,current_user:CurrentShiftPlannerUser):service.delete_shift(db,current_user,shift_id);return Response(status_code=204)
