from datetime import date,datetime
from decimal import Decimal
from uuid import uuid4
from sqlalchemy import Date,DateTime,ForeignKey,Index,Integer,Numeric,String,Text,func
from sqlalchemy.orm import Mapped,mapped_column,relationship
from app.modules.savings_goal_planner.db import Base
def uid():return str(uuid4())
class Goal(Base):
 __tablename__="SavingsGoals";__table_args__=(Index("ix_savings_goals_user_status","userId","status"),Index("ix_savings_goals_user_target_date","userId","targetDate"),Index("ix_savings_goals_user_currency","userId","currencyCode"),Index("ix_savings_goals_user_category","userId","category"))
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);owner_id:Mapped[str]=mapped_column("userId",String(36),index=True);name:Mapped[str]=mapped_column(String(180));description:Mapped[str|None]=mapped_column(Text);category:Mapped[str]=mapped_column(String(24),index=True);currency_code:Mapped[str]=mapped_column("currencyCode",String(3));target_amount:Mapped[Decimal]=mapped_column("targetAmount",Numeric(14,2));starting_amount:Mapped[Decimal]=mapped_column("startingAmount",Numeric(14,2));current_amount:Mapped[Decimal]=mapped_column("currentAmount",Numeric(14,2));target_date:Mapped[date|None]=mapped_column("targetDate",Date,index=True);priority:Mapped[str]=mapped_column(String(12),index=True);status:Mapped[str]=mapped_column(String(16),index=True);notes:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column("createdAt",DateTime(),server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime(),server_default=func.now(),onupdate=func.now());transactions:Mapped[list["Transaction"]]=relationship(back_populates="goal",cascade="all, delete-orphan");milestones:Mapped[list["Milestone"]]=relationship(back_populates="goal",cascade="all, delete-orphan")
class Transaction(Base):
 __tablename__="SavingsTransactions";__table_args__=(Index("ix_savings_transactions_goal_date","goalId","transactionDate"),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);goal_id:Mapped[str]=mapped_column("goalId",String(36),ForeignKey("SavingsGoals.id",ondelete="CASCADE"),index=True);transaction_date:Mapped[date]=mapped_column("transactionDate",Date,index=True);transaction_type:Mapped[str]=mapped_column("transactionType",String(24),index=True);amount:Mapped[Decimal]=mapped_column(Numeric(14,2));description:Mapped[str|None]=mapped_column(String(300));notes:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column("createdAt",DateTime(),server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime(),server_default=func.now(),onupdate=func.now());goal:Mapped[Goal]=relationship(back_populates="transactions")
class Milestone(Base):
 __tablename__="SavingsMilestones";__table_args__=(Index("ix_savings_milestones_goal_sort","goalId","sortOrder"),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);goal_id:Mapped[str]=mapped_column("goalId",String(36),ForeignKey("SavingsGoals.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(180));target_amount:Mapped[Decimal]=mapped_column("targetAmount",Numeric(14,2));target_date:Mapped[date|None]=mapped_column("targetDate",Date);status:Mapped[str]=mapped_column(String(16));sort_order:Mapped[int]=mapped_column("sortOrder",Integer);notes:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column("createdAt",DateTime(),server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime(),server_default=func.now(),onupdate=func.now());goal:Mapped[Goal]=relationship(back_populates="milestones")
