from datetime import date,datetime
from decimal import Decimal
from uuid import uuid4
from sqlalchemy import Date,DateTime,ForeignKey,Index,Integer,Numeric,String,Text,UniqueConstraint,func
from sqlalchemy.orm import Mapped,mapped_column,relationship
from app.modules.bill_splitter.db import Base
def uid():return str(uuid4())
class Bill(Base):
 __tablename__="Bills";__table_args__=(Index("ix_bills_user_date","userId","billDate"),Index("ix_bills_user_status","userId","status"),Index("ix_bills_user_currency","userId","currencyCode"))
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);owner_id:Mapped[str]=mapped_column("userId",String(36),index=True);title:Mapped[str]=mapped_column(String(180));bill_date:Mapped[date]=mapped_column("billDate",Date,index=True);merchant_name:Mapped[str|None]=mapped_column("merchantName",String(180));currency_code:Mapped[str]=mapped_column("currencyCode",String(3));discount_amount:Mapped[Decimal]=mapped_column("discountAmount",Numeric(14,2),default=0);tax_amount:Mapped[Decimal]=mapped_column("taxAmount",Numeric(14,2),default=0);service_charge_amount:Mapped[Decimal]=mapped_column("serviceChargeAmount",Numeric(14,2),default=0);tip_amount:Mapped[Decimal]=mapped_column("tipAmount",Numeric(14,2),default=0);subtotal_amount:Mapped[Decimal]=mapped_column("subtotalAmount",Numeric(14,2),default=0);total_amount:Mapped[Decimal]=mapped_column("totalAmount",Numeric(14,2),default=0);status:Mapped[str]=mapped_column(String(24),index=True);notes:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column("createdAt",DateTime(),server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime(),server_default=func.now(),onupdate=func.now());participants:Mapped[list["Participant"]]=relationship(back_populates="bill",cascade="all, delete-orphan");items:Mapped[list["Item"]]=relationship(back_populates="bill",cascade="all, delete-orphan")
class Participant(Base):
 __tablename__="BillParticipants";__table_args__=(UniqueConstraint("billId","name",name="uq_bill_participant_name"),Index("ix_bill_participants_bill_sort","billId","sortOrder"))
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);bill_id:Mapped[str]=mapped_column("billId",String(36),ForeignKey("Bills.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(120));email:Mapped[str|None]=mapped_column(String(254));paid_amount:Mapped[Decimal]=mapped_column("paidAmount",Numeric(14,2),default=0);share_amount:Mapped[Decimal]=mapped_column("shareAmount",Numeric(14,2),default=0);settlement_status:Mapped[str]=mapped_column("settlementStatus",String(24),default="unpaid");notes:Mapped[str|None]=mapped_column(Text);sort_order:Mapped[int]=mapped_column("sortOrder",Integer,default=0);created_at:Mapped[datetime]=mapped_column("createdAt",DateTime(),server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime(),server_default=func.now(),onupdate=func.now());bill:Mapped[Bill]=relationship(back_populates="participants");allocations:Mapped[list["Allocation"]]=relationship(back_populates="participant")
class Item(Base):
 __tablename__="BillItems";__table_args__=(Index("ix_bill_items_bill_sort","billId","sortOrder"),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);bill_id:Mapped[str]=mapped_column("billId",String(36),ForeignKey("Bills.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(180));quantity:Mapped[Decimal]=mapped_column(Numeric(12,2));unit_price:Mapped[Decimal]=mapped_column("unitPrice",Numeric(14,2));line_total:Mapped[Decimal]=mapped_column("lineTotal",Numeric(14,2));split_method:Mapped[str]=mapped_column("splitMethod",String(24),default="equal");notes:Mapped[str|None]=mapped_column(Text);sort_order:Mapped[int]=mapped_column("sortOrder",Integer,default=0);created_at:Mapped[datetime]=mapped_column("createdAt",DateTime(),server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime(),server_default=func.now(),onupdate=func.now());bill:Mapped[Bill]=relationship(back_populates="items");allocations:Mapped[list["Allocation"]]=relationship(back_populates="item",cascade="all, delete-orphan")
class Allocation(Base):
 __tablename__="BillItemAllocations";__table_args__=(UniqueConstraint("billItemId","participantId",name="uq_item_participant"),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);item_id:Mapped[str]=mapped_column("billItemId",String(36),ForeignKey("BillItems.id",ondelete="CASCADE"),index=True);participant_id:Mapped[str]=mapped_column("participantId",String(36),ForeignKey("BillParticipants.id"),index=True);allocation_amount:Mapped[Decimal]=mapped_column("allocationAmount",Numeric(14,2));created_at:Mapped[datetime]=mapped_column("createdAt",DateTime(),server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime(),server_default=func.now(),onupdate=func.now());item:Mapped[Item]=relationship(back_populates="allocations");participant:Mapped[Participant]=relationship(back_populates="allocations")
