from datetime import date,datetime
from decimal import Decimal
from uuid import uuid4
from sqlalchemy import Boolean,Date,DateTime,ForeignKey,Index,Integer,Numeric,String,Text,UniqueConstraint,func
from sqlalchemy.orm import Mapped,mapped_column,relationship
from .db import Base
def uid():return str(uuid4())
class Decision(Base):
 __tablename__="Decisions";__table_args__=(Index("ix_decisions_user_status","userId","status"),Index("ix_decisions_user_type","userId","decisionType"),Index("ix_decisions_user_target","userId","targetDate"),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);user_id:Mapped[str]=mapped_column("userId",String(36),index=True);title:Mapped[str]=mapped_column(String(180));question:Mapped[str]=mapped_column(Text);description:Mapped[str|None]=mapped_column(Text);decision_type:Mapped[str]=mapped_column("decisionType",String(20));rating_scale:Mapped[int]=mapped_column("ratingScale",Integer);status:Mapped[str]=mapped_column(String(15));target_date:Mapped[date|None]=mapped_column("targetDate",Date);selected_option_id:Mapped[str|None]=mapped_column("selectedOptionId",String(36));outcome:Mapped[str|None]=mapped_column(Text);reflection:Mapped[str|None]=mapped_column(Text);notes:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column("createdAt",DateTime,server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime,server_default=func.now(),onupdate=func.now());decided_at:Mapped[datetime|None]=mapped_column("decidedAt",DateTime);options:Mapped[list["Option"]]=relationship(cascade="all, delete-orphan");criteria:Mapped[list["Criterion"]]=relationship(cascade="all, delete-orphan");ratings:Mapped[list["Rating"]]=relationship(cascade="all, delete-orphan")
class Option(Base):
 __tablename__="DecisionOptions";__table_args__=(UniqueConstraint("decisionId","name",name="uq_decision_option_name"),Index("ix_decision_options_sort","decisionId","sortOrder"),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);decision_id:Mapped[str]=mapped_column("decisionId",String(36),ForeignKey("Decisions.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(180));description:Mapped[str|None]=mapped_column(Text);pros:Mapped[str|None]=mapped_column(Text);cons:Mapped[str|None]=mapped_column(Text);risks:Mapped[str|None]=mapped_column(Text);assumptions:Mapped[str|None]=mapped_column(Text);notes:Mapped[str|None]=mapped_column(Text);sort_order:Mapped[int]=mapped_column("sortOrder",Integer);is_active:Mapped[bool]=mapped_column("isActive",Boolean);created_at:Mapped[datetime]=mapped_column("createdAt",DateTime,server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime,server_default=func.now(),onupdate=func.now())
class Criterion(Base):
 __tablename__="DecisionCriteria";__table_args__=(UniqueConstraint("decisionId","name",name="uq_decision_criterion_name"),Index("ix_decision_criteria_sort","decisionId","sortOrder"),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);decision_id:Mapped[str]=mapped_column("decisionId",String(36),ForeignKey("Decisions.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(180));description:Mapped[str|None]=mapped_column(Text);weight:Mapped[Decimal]=mapped_column(Numeric(10,2));direction:Mapped[str]=mapped_column(String(20));sort_order:Mapped[int]=mapped_column("sortOrder",Integer);is_active:Mapped[bool]=mapped_column("isActive",Boolean);created_at:Mapped[datetime]=mapped_column("createdAt",DateTime,server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime,server_default=func.now(),onupdate=func.now())
class Rating(Base):
 __tablename__="DecisionRatings";__table_args__=(UniqueConstraint("optionId","criterionId",name="uq_decision_rating_pair"),Index("ix_decision_ratings_decision","decisionId"),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);decision_id:Mapped[str]=mapped_column("decisionId",String(36),ForeignKey("Decisions.id",ondelete="CASCADE"));option_id:Mapped[str]=mapped_column("optionId",String(36),ForeignKey("DecisionOptions.id",ondelete="CASCADE"));criterion_id:Mapped[str]=mapped_column("criterionId",String(36),ForeignKey("DecisionCriteria.id",ondelete="CASCADE"));rating:Mapped[int]=mapped_column(Integer);notes:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column("createdAt",DateTime,server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime,server_default=func.now(),onupdate=func.now())
