from datetime import date
from fastapi import APIRouter,Query,Response
from . import service as s
from .dependencies import CurrentUser,DB
from .schemas import *
router=APIRouter()
@router.get("/dashboard",response_model=Dashboard,operation_id="getDecisionMakerDashboard")
def dashboard(db:DB,current_user:CurrentUser):return s.dashboard(db,current_user)
@router.get("/decisions",response_model=DecisionList,operation_id="listDecisions")
def decisions(db:DB,current_user:CurrentUser,q:str|None=None,status:Status|None=None,decision_type:DecisionType|None=Query(None,alias="decisionType"),due_soon:bool|None=Query(None,alias="dueSoon"),overdue:bool|None=None,created_from:date|None=Query(None,alias="createdFrom"),created_to:date|None=Query(None,alias="createdTo"),updated_from:date|None=Query(None,alias="updatedFrom"),updated_to:date|None=Query(None,alias="updatedTo"),page:int=Query(1,ge=1),page_size:int=Query(12,alias="pageSize",ge=1,le=100)):return s.list_decisions(db,current_user,q,status,decision_type,due_soon,overdue,created_from,created_to,updated_from,updated_to,page,page_size)
@router.post("/decisions",response_model=DecisionDetail,status_code=201,operation_id="createDecision")
def create(payload:DecisionCreate,db:DB,current_user:CurrentUser):return s.save_decision(db,current_user,payload)
@router.get("/decisions/{decision_id}",response_model=DecisionDetail,operation_id="getDecision")
def get(decision_id:str,db:DB,current_user:CurrentUser):return s.get(db,current_user,decision_id)
@router.put("/decisions/{decision_id}",response_model=DecisionDetail,operation_id="updateDecision")
def update(decision_id:str,payload:DecisionUpdate,db:DB,current_user:CurrentUser):return s.save_decision(db,current_user,payload,decision_id)
@router.delete("/decisions/{decision_id}",status_code=204,operation_id="deleteDecision")
def delete(decision_id:str,db:DB,current_user:CurrentUser):s.delete_decision(db,current_user,decision_id);return Response(status_code=204)
@router.post("/decisions/{decision_id}/options",response_model=DecisionDetail,status_code=201,operation_id="createDecisionOption")
def co(decision_id:str,payload:OptionCreate,db:DB,current_user:CurrentUser):return s.save_option(db,current_user,decision_id,payload)
@router.put("/decisions/{decision_id}/options/{option_id}",response_model=DecisionDetail,operation_id="updateDecisionOption")
def uo(decision_id:str,option_id:str,payload:OptionUpdate,db:DB,current_user:CurrentUser):return s.save_option(db,current_user,decision_id,payload,option_id)
@router.delete("/decisions/{decision_id}/options/{option_id}",status_code=204,operation_id="deleteDecisionOption")
def do(decision_id:str,option_id:str,db:DB,current_user:CurrentUser):s.delete_option(db,current_user,decision_id,option_id);return Response(status_code=204)
@router.post("/decisions/{decision_id}/criteria",response_model=DecisionDetail,status_code=201,operation_id="createDecisionCriterion")
def cc(decision_id:str,payload:CriterionCreate,db:DB,current_user:CurrentUser):return s.save_criterion(db,current_user,decision_id,payload)
@router.put("/decisions/{decision_id}/criteria/{criterion_id}",response_model=DecisionDetail,operation_id="updateDecisionCriterion")
def uc(decision_id:str,criterion_id:str,payload:CriterionUpdate,db:DB,current_user:CurrentUser):return s.save_criterion(db,current_user,decision_id,payload,criterion_id)
@router.delete("/decisions/{decision_id}/criteria/{criterion_id}",status_code=204,operation_id="deleteDecisionCriterion")
def dc(decision_id:str,criterion_id:str,db:DB,current_user:CurrentUser):s.delete_criterion(db,current_user,decision_id,criterion_id);return Response(status_code=204)
@router.put("/decisions/{decision_id}/ratings",response_model=DecisionDetail,operation_id="upsertDecisionRatings")
def ratings(decision_id:str,payload:RatingMatrix,db:DB,current_user:CurrentUser):return s.upsert_ratings(db,current_user,decision_id,payload)
@router.delete("/decisions/{decision_id}/ratings/{rating_id}",status_code=204,operation_id="deleteDecisionRating")
def dr(decision_id:str,rating_id:str,db:DB,current_user:CurrentUser):s.delete_rating(db,current_user,decision_id,rating_id);return Response(status_code=204)
