"""Create Work Log Tracker tables."""
from alembic import op
import sqlalchemy as sa
revision="20260716_0004_work_log_tracker";down_revision=None;branch_labels=None;depends_on=None
def upgrade():
 op.create_table("WorkProjects",sa.Column("id",sa.String(36),primary_key=True),sa.Column("userId",sa.String(36),nullable=False),sa.Column("name",sa.String(120),nullable=False),sa.Column("code",sa.String(30)),sa.Column("clientName",sa.String(120)),sa.Column("description",sa.Text()),sa.Column("defaultBillable",sa.Boolean(),nullable=False),sa.Column("isActive",sa.Boolean(),nullable=False),sa.Column("createdAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updatedAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.UniqueConstraint("userId","name"),sa.UniqueConstraint("userId","code"));op.create_index("ix_work_projects_user_id","WorkProjects",["userId"]);op.create_index("ix_work_projects_user_active","WorkProjects",["userId","isActive"])
 op.create_table("WorkLogs",sa.Column("id",sa.String(36),primary_key=True),sa.Column("userId",sa.String(36),nullable=False),sa.Column("projectId",sa.String(36),sa.ForeignKey("WorkProjects.id"),nullable=False),sa.Column("title",sa.String(180),nullable=False),sa.Column("workDate",sa.Date(),nullable=False),sa.Column("startTime",sa.Time()),sa.Column("endTime",sa.Time()),sa.Column("durationMinutes",sa.Integer(),nullable=False),sa.Column("breakMinutes",sa.Integer(),nullable=False),sa.Column("entryMode",sa.String(20),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("isBillable",sa.Boolean(),nullable=False),sa.Column("accomplishments",sa.Text()),sa.Column("blockers",sa.Text()),sa.Column("notes",sa.Text()),sa.Column("createdAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updatedAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False))
 for n,c in [("ix_work_logs_user_id",["userId"]),("ix_work_logs_project_id",["projectId"]),("ix_work_logs_date",["workDate"]),("ix_work_logs_entry_mode",["entryMode"]),("ix_work_logs_status",["status"]),("ix_work_logs_billable",["isBillable"]),("ix_work_logs_user_date",["userId","workDate"]),("ix_work_logs_user_status",["userId","status"]),("ix_work_logs_user_project_date",["userId","projectId","workDate"])]:op.create_index(n,"WorkLogs",c)
def downgrade():op.drop_table("WorkLogs");op.drop_table("WorkProjects")
