from datetime import date,datetime
from decimal import Decimal
from uuid import uuid4
from sqlalchemy import Boolean,Date,DateTime,ForeignKey,Index,Integer,Numeric,String,Text,func
from sqlalchemy.orm import Mapped,mapped_column,relationship
from app.modules.salary_breakdown_calculator.db import Base
def uid():return str(uuid4())
class Scenario(Base):
 __tablename__="SalaryScenarios";__table_args__=(Index("ix_salary_scenarios_user_status","userId","status"),Index("ix_salary_scenarios_user_frequency","userId","payFrequency"),Index("ix_salary_scenarios_user_currency","userId","currencyCode"))
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);owner_id:Mapped[str]=mapped_column("userId",String(36),index=True);name:Mapped[str]=mapped_column(String(180));description:Mapped[str|None]=mapped_column(Text);currency_code:Mapped[str]=mapped_column("currencyCode",String(3));pay_frequency:Mapped[str]=mapped_column("payFrequency",String(20),index=True);base_salary_amount:Mapped[Decimal]=mapped_column("baseSalaryAmount",Numeric(14,2));base_salary_period:Mapped[str]=mapped_column("baseSalaryPeriod",String(20));working_days_per_week:Mapped[Decimal]=mapped_column("workingDaysPerWeek",Numeric(4,2));working_hours_per_week:Mapped[Decimal]=mapped_column("workingHoursPerWeek",Numeric(5,2));status:Mapped[str]=mapped_column(String(12),index=True);notes:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column("createdAt",DateTime(),server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime(),server_default=func.now(),onupdate=func.now());earnings:Mapped[list["Earning"]]=relationship(cascade="all, delete-orphan");deductions:Mapped[list["Deduction"]]=relationship(cascade="all, delete-orphan")
class Earning(Base):
 __tablename__="SalaryEarnings";__table_args__=(Index("ix_salary_earnings_scenario_sort","scenarioId","sortOrder"),);id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);scenario_id:Mapped[str]=mapped_column("scenarioId",String(36),ForeignKey("SalaryScenarios.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(180));earning_type:Mapped[str]=mapped_column("earningType",String(20));amount:Mapped[Decimal]=mapped_column(Numeric(14,2));frequency:Mapped[str]=mapped_column(String(20));is_taxable:Mapped[bool]=mapped_column("isTaxable",Boolean);is_recurring:Mapped[bool]=mapped_column("isRecurring",Boolean);effective_date:Mapped[date|None]=mapped_column("effectiveDate",Date);notes:Mapped[str|None]=mapped_column(Text);sort_order:Mapped[int]=mapped_column("sortOrder",Integer);created_at:Mapped[datetime]=mapped_column("createdAt",DateTime(),server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime(),server_default=func.now(),onupdate=func.now())
class Deduction(Base):
 __tablename__="SalaryDeductions";__table_args__=(Index("ix_salary_deductions_scenario_sort","scenarioId","sortOrder"),);id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);scenario_id:Mapped[str]=mapped_column("scenarioId",String(36),ForeignKey("SalaryScenarios.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(180));deduction_type:Mapped[str]=mapped_column("deductionType",String(20));calculation_method:Mapped[str]=mapped_column("calculationMethod",String(24));amount:Mapped[Decimal|None]=mapped_column(Numeric(14,2));percentage:Mapped[Decimal|None]=mapped_column(Numeric(7,4));frequency:Mapped[str]=mapped_column(String(20));is_recurring:Mapped[bool]=mapped_column("isRecurring",Boolean);effective_date:Mapped[date|None]=mapped_column("effectiveDate",Date);notes:Mapped[str|None]=mapped_column(Text);sort_order:Mapped[int]=mapped_column("sortOrder",Integer);created_at:Mapped[datetime]=mapped_column("createdAt",DateTime(),server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime(),server_default=func.now(),onupdate=func.now())
