from datetime import datetime
from uuid import uuid4
from sqlalchemy import Boolean,DateTime,ForeignKey,Index,Integer,String,Text,UniqueConstraint,func
from sqlalchemy.orm import Mapped,mapped_column,relationship
from .db import Base
def uid():return str(uuid4())
class ChecklistCategory(Base):
 __tablename__="ChecklistCategories";__table_args__=(UniqueConstraint("userId","name",name="uq_checklist_category_user_name"),Index("ix_checklist_categories_user_sort","userId","sortOrder"),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);user_id:Mapped[str]=mapped_column("userId",String(36),index=True);name:Mapped[str]=mapped_column(String(80));color:Mapped[str|None]=mapped_column(String(40));sort_order:Mapped[int]=mapped_column("sortOrder",Integer,default=0);created_at:Mapped[datetime]=mapped_column("createdAt",DateTime,server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime,server_default=func.now(),onupdate=func.now());checklists:Mapped[list["EmergencyChecklist"]]=relationship(back_populates="category")
class EmergencyChecklist(Base):
 __tablename__="EmergencyChecklists";__table_args__=(UniqueConstraint("userId","categoryId","title",name="uq_emergency_checklist_user_category_title"),Index("ix_emergency_checklists_user_category","userId","categoryId"),Index("ix_emergency_checklists_user_archived","userId","archived"),Index("ix_emergency_checklists_user_updated","userId","updatedAt"),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);user_id:Mapped[str]=mapped_column("userId",String(36),index=True);category_id:Mapped[str|None]=mapped_column("categoryId",String(36),ForeignKey("ChecklistCategories.id",ondelete="SET NULL"),index=True);title:Mapped[str]=mapped_column(String(180));description:Mapped[str|None]=mapped_column(Text);archived:Mapped[bool]=mapped_column(Boolean,default=False);created_at:Mapped[datetime]=mapped_column("createdAt",DateTime,server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime,server_default=func.now(),onupdate=func.now());category:Mapped[ChecklistCategory|None]=relationship(back_populates="checklists");items:Mapped[list["ChecklistItem"]]=relationship(back_populates="checklist",cascade="all, delete-orphan",order_by="ChecklistItem.sort_order")
class ChecklistItem(Base):
 __tablename__="ChecklistItems";__table_args__=(Index("ix_checklist_items_checklist_sort","checklistId","sortOrder"),Index("ix_checklist_items_checklist_completed","checklistId","completed"),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);checklist_id:Mapped[str]=mapped_column("checklistId",String(36),ForeignKey("EmergencyChecklists.id",ondelete="CASCADE"),index=True);title:Mapped[str]=mapped_column(String(180));notes:Mapped[str|None]=mapped_column(Text);completed:Mapped[bool]=mapped_column(Boolean,default=False);sort_order:Mapped[int]=mapped_column("sortOrder",Integer,default=0);created_at:Mapped[datetime]=mapped_column("createdAt",DateTime,server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime,server_default=func.now(),onupdate=func.now());checklist:Mapped[EmergencyChecklist]=relationship(back_populates="items")
