from typing import Literal
from fastapi import APIRouter,Query,Response
from . import service as s
from .dependencies import CurrentUser,DB
from .schemas import *
router=APIRouter()
@router.get("/dashboard",response_model=EmergencyDashboard,operation_id="getEmergencyChecklistDashboard")
def dashboard(db:DB,current_user:CurrentUser):return s.dashboard(db,current_user)
@router.get("/checklists",response_model=EmergencyChecklistList,operation_id="listEmergencyChecklists")
def checklists(db:DB,current_user:CurrentUser,q:str|None=None,category_id:str|None=Query(None,alias="categoryId"),archived:bool|None=None,completion:Literal["completed","incomplete"]|None=None,page:int=Query(1,ge=1),page_size:int=Query(12,alias="pageSize",ge=1,le=100)):return s.list_checklists(db,current_user,q,category_id,archived,completion,page,page_size)
@router.post("/checklists",response_model=EmergencyChecklistDetail,status_code=201,operation_id="createEmergencyChecklist")
def create_checklist(payload:EmergencyChecklistCreate,db:DB,current_user:CurrentUser):return s.save_checklist(db,current_user,payload)
@router.get("/checklists/{checklist_id}",response_model=EmergencyChecklistDetail,operation_id="getEmergencyChecklist")
def get_checklist(checklist_id:str,db:DB,current_user:CurrentUser):return s.get_checklist(db,current_user,checklist_id)
@router.put("/checklists/{checklist_id}",response_model=EmergencyChecklistDetail,operation_id="updateEmergencyChecklist")
def update_checklist(checklist_id:str,payload:EmergencyChecklistUpdate,db:DB,current_user:CurrentUser):return s.save_checklist(db,current_user,payload,checklist_id)
@router.delete("/checklists/{checklist_id}",status_code=204,operation_id="deleteEmergencyChecklist")
def delete_checklist(checklist_id:str,db:DB,current_user:CurrentUser):s.delete_checklist(db,current_user,checklist_id);return Response(status_code=204)
@router.post("/checklists/{checklist_id}/archive",response_model=EmergencyChecklistDetail,operation_id="archiveEmergencyChecklist")
def archive(checklist_id:str,db:DB,current_user:CurrentUser):return s.archive(db,current_user,checklist_id)
@router.post("/checklists/{checklist_id}/restore",response_model=EmergencyChecklistDetail,operation_id="restoreEmergencyChecklist")
def restore(checklist_id:str,db:DB,current_user:CurrentUser):return s.restore(db,current_user,checklist_id)
@router.post("/checklists/{checklist_id}/reset",response_model=EmergencyChecklistDetail,operation_id="resetEmergencyChecklist")
def reset(checklist_id:str,db:DB,current_user:CurrentUser):return s.reset(db,current_user,checklist_id)
@router.post("/checklists/{checklist_id}/complete",response_model=EmergencyChecklistDetail,operation_id="completeEmergencyChecklist")
def complete(checklist_id:str,db:DB,current_user:CurrentUser):return s.complete_all(db,current_user,checklist_id)
@router.post("/checklists/{checklist_id}/items",response_model=EmergencyChecklistDetail,status_code=201,operation_id="createEmergencyChecklistItem")
def create_item(checklist_id:str,payload:ChecklistItemCreate,db:DB,current_user:CurrentUser):return s.save_item(db,current_user,checklist_id,payload)
@router.put("/checklists/{checklist_id}/items/{item_id}",response_model=EmergencyChecklistDetail,operation_id="updateEmergencyChecklistItem")
def update_item(checklist_id:str,item_id:str,payload:ChecklistItemUpdate,db:DB,current_user:CurrentUser):return s.save_item(db,current_user,checklist_id,payload,item_id)
@router.post("/checklists/{checklist_id}/items/{item_id}/complete",response_model=EmergencyChecklistDetail,operation_id="completeEmergencyChecklistItem")
def complete_item(checklist_id:str,item_id:str,db:DB,current_user:CurrentUser):return s.toggle_item(db,current_user,checklist_id,item_id,True)
@router.post("/checklists/{checklist_id}/items/{item_id}/reopen",response_model=EmergencyChecklistDetail,operation_id="reopenEmergencyChecklistItem")
def reopen_item(checklist_id:str,item_id:str,db:DB,current_user:CurrentUser):return s.toggle_item(db,current_user,checklist_id,item_id,False)
@router.delete("/checklists/{checklist_id}/items/{item_id}",response_model=EmergencyChecklistDetail,operation_id="deleteEmergencyChecklistItem")
def delete_item(checklist_id:str,item_id:str,db:DB,current_user:CurrentUser):return s.delete_item(db,current_user,checklist_id,item_id)
@router.get("/categories",response_model=EmergencyCategoryList,operation_id="listEmergencyChecklistCategories")
def categories(db:DB,current_user:CurrentUser,q:str|None=None,page:int=Query(1,ge=1),page_size:int=Query(50,alias="pageSize",ge=1,le=100)):return s.list_categories(db,current_user,q,page,page_size)
@router.post("/categories",response_model=EmergencyCategoryResponse,status_code=201,operation_id="createEmergencyChecklistCategory")
def create_category(payload:EmergencyCategoryCreate,db:DB,current_user:CurrentUser):return s.save_category(db,current_user,payload)
@router.put("/categories/{category_id}",response_model=EmergencyCategoryResponse,operation_id="updateEmergencyChecklistCategory")
def update_category(category_id:str,payload:EmergencyCategoryUpdate,db:DB,current_user:CurrentUser):return s.save_category(db,current_user,payload,category_id)
@router.delete("/categories/{category_id}",status_code=204,operation_id="deleteEmergencyChecklistCategory")
def delete_category(category_id:str,db:DB,current_user:CurrentUser):s.delete_category(db,current_user,category_id);return Response(status_code=204)
