"""Create Salary Breakdown Calculator tables."""
from alembic import op
import sqlalchemy as sa
revision="20260716_0007_salary_breakdown_calculator";down_revision=None;branch_labels=None;depends_on=None
M=sa.Numeric(14,2)
def upgrade():
 op.create_table("SalaryScenarios",sa.Column("id",sa.String(36),primary_key=True),sa.Column("userId",sa.String(36),nullable=False),sa.Column("name",sa.String(180),nullable=False),sa.Column("description",sa.Text()),sa.Column("currencyCode",sa.String(3),nullable=False),sa.Column("payFrequency",sa.String(20),nullable=False),sa.Column("baseSalaryAmount",M,nullable=False),sa.Column("baseSalaryPeriod",sa.String(20),nullable=False),sa.Column("workingDaysPerWeek",sa.Numeric(4,2),nullable=False),sa.Column("workingHoursPerWeek",sa.Numeric(5,2),nullable=False),sa.Column("status",sa.String(12),nullable=False),sa.Column("notes",sa.Text()),sa.Column("createdAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updatedAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False))
 for n,c in [("ix_salary_scenarios_user_id",["userId"]),("ix_salary_scenarios_frequency",["payFrequency"]),("ix_salary_scenarios_status",["status"]),("ix_salary_scenarios_user_status",["userId","status"]),("ix_salary_scenarios_user_frequency",["userId","payFrequency"]),("ix_salary_scenarios_user_currency",["userId","currencyCode"])]:op.create_index(n,"SalaryScenarios",c)
 op.create_table("SalaryEarnings",sa.Column("id",sa.String(36),primary_key=True),sa.Column("scenarioId",sa.String(36),sa.ForeignKey("SalaryScenarios.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(180),nullable=False),sa.Column("earningType",sa.String(20),nullable=False),sa.Column("amount",M,nullable=False),sa.Column("frequency",sa.String(20),nullable=False),sa.Column("isTaxable",sa.Boolean(),nullable=False),sa.Column("isRecurring",sa.Boolean(),nullable=False),sa.Column("effectiveDate",sa.Date()),sa.Column("notes",sa.Text()),sa.Column("sortOrder",sa.Integer(),nullable=False),sa.Column("createdAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updatedAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False));op.create_index("ix_salary_earnings_scenario_id","SalaryEarnings",["scenarioId"]);op.create_index("ix_salary_earnings_scenario_sort","SalaryEarnings",["scenarioId","sortOrder"])
 op.create_table("SalaryDeductions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("scenarioId",sa.String(36),sa.ForeignKey("SalaryScenarios.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(180),nullable=False),sa.Column("deductionType",sa.String(20),nullable=False),sa.Column("calculationMethod",sa.String(24),nullable=False),sa.Column("amount",M),sa.Column("percentage",sa.Numeric(7,4)),sa.Column("frequency",sa.String(20),nullable=False),sa.Column("isRecurring",sa.Boolean(),nullable=False),sa.Column("effectiveDate",sa.Date()),sa.Column("notes",sa.Text()),sa.Column("sortOrder",sa.Integer(),nullable=False),sa.Column("createdAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updatedAt",sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False));op.create_index("ix_salary_deductions_scenario_id","SalaryDeductions",["scenarioId"]);op.create_index("ix_salary_deductions_scenario_sort","SalaryDeductions",["scenarioId","sortOrder"])
def downgrade():op.drop_table("SalaryDeductions");op.drop_table("SalaryEarnings");op.drop_table("SalaryScenarios")
