from datetime import date,datetime,time
from uuid import uuid4
from sqlalchemy import Boolean,Date,DateTime,ForeignKey,Index,Integer,String,Text,Time,UniqueConstraint,func
from sqlalchemy.orm import Mapped,mapped_column,relationship
from app.modules.work_log_tracker.db import WorkLogBase
def uid():return str(uuid4())
class WorkProject(WorkLogBase):
 __tablename__="WorkProjects";__table_args__=(UniqueConstraint("userId","name",name="uq_work_projects_user_name"),UniqueConstraint("userId","code",name="uq_work_projects_user_code"),Index("ix_work_projects_user_active","userId","isActive"))
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);owner_id:Mapped[str]=mapped_column("userId",String(36),index=True);name:Mapped[str]=mapped_column(String(120));code:Mapped[str|None]=mapped_column(String(30));client_name:Mapped[str|None]=mapped_column("clientName",String(120));description:Mapped[str|None]=mapped_column(Text);default_billable:Mapped[bool]=mapped_column("defaultBillable",Boolean,default=False);is_active:Mapped[bool]=mapped_column("isActive",Boolean,default=True);created_at:Mapped[datetime]=mapped_column("createdAt",DateTime(timezone=True),server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime(timezone=True),server_default=func.now(),onupdate=func.now());logs:Mapped[list["WorkLog"]]=relationship(back_populates="project")
class WorkLog(WorkLogBase):
 __tablename__="WorkLogs";__table_args__=(Index("ix_work_logs_user_date","userId","workDate"),Index("ix_work_logs_user_status","userId","status"),Index("ix_work_logs_user_project_date","userId","projectId","workDate"))
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);owner_id:Mapped[str]=mapped_column("userId",String(36),index=True);project_id:Mapped[str]=mapped_column("projectId",String(36),ForeignKey("WorkProjects.id"),index=True);title:Mapped[str]=mapped_column(String(180));work_date:Mapped[date]=mapped_column("workDate",Date,index=True);start_time:Mapped[time|None]=mapped_column("startTime",Time);end_time:Mapped[time|None]=mapped_column("endTime",Time);duration_minutes:Mapped[int]=mapped_column("durationMinutes",Integer);break_minutes:Mapped[int]=mapped_column("breakMinutes",Integer,default=0);entry_mode:Mapped[str]=mapped_column("entryMode",String(20),index=True);status:Mapped[str]=mapped_column(String(20),index=True);is_billable:Mapped[bool]=mapped_column("isBillable",Boolean,index=True);accomplishments:Mapped[str|None]=mapped_column(Text);blockers:Mapped[str|None]=mapped_column(Text);notes:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column("createdAt",DateTime(timezone=True),server_default=func.now());updated_at:Mapped[datetime]=mapped_column("updatedAt",DateTime(timezone=True),server_default=func.now(),onupdate=func.now());project:Mapped[WorkProject]=relationship(back_populates="logs")
